[package]
name = "project-explainer-os"
version = "0.1.0"
description = "Project Explainer OS"
authors = ["you"]
edition = "2021"

[lib]
name = "project_explainer_os_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"

serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "blocking"] }

rusqlite = { version = "0.32", features = ["bundled"] }
walkdir = "2"
regex = "1"
chrono = { version = "0.4", features = ["serde"] }

dotenvy = "0.15"
dirs = "5"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
